before_install:
    - gem install cocoapods
language: objective-c
xcode_workspace: DrawInQuad.xcworkspace
osx_image: xcode9.2
matrix:
  include:
    - xcode_scheme: DrawInQuad
      script: 'xcodebuild clean &&
      xcodebuild build -sdk iphonesimulator11.2 -project DrawInQuad.xcodeproj -scheme DrawInQuad'
    - xcode_scheme: DrawInQuad
      script: 'xcodebuild clean &&
      xcodebuild build -sdk iphonesimulator11.2 -project DrawInQuad.xcodeproj -scheme CGTextureMapping'
